services:
  smart-bin-frontend:
    # 1. 构建阶段：使用当前目录（包含 Dockerfile 的目录）
    build:
      context: .          # Dockerfile 所在目录
      dockerfile: Dockerfile

    # 2. 运行阶段：镜像名/标签
    image: ziptako/smart-bin-frontend:latest   # 构建成功后会给镜像打这个 tag

    # 3. 端口映射（示例：宿主机 8080 → 容器 80）
    #ports:
    #  - "3000:3000" 服务器环境可以不映射，通过nginx网络代理

    # 4. 环境变量
    environment:
      - NODE_ENV=production
      - TZ=Asia/Shanghai

    # 6. 重启策略
    restart: unless-stopped